name: Build CI

on:
    push:
        branches:
            - main
            - latest

    pull_request:
        branches:
            - main
            - latest

jobs:
    build:
        name: Check if the project can be build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the project
              uses: actions/checkout@v2

            - name: Setup for the environment
              run: cp .env.example .env

            - name: Setting NODE_ENV
              run: sed -i 's/NODE_ENV=.*/NODE_ENV=development/g' .env

            - name: Install the Node.js dependencies
              run: make install peer

            - name: Check if the project can be build
              run: make build
